X-sSweetShop/Controllers/PieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using X_sSweetShop.Models;
using X_sSweetShop.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace X_sSweetShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List()
        {
            PiesListViewModel piesListViewModel = new PiesListViewModel();
            piesListViewModel.Pies = _pieRepository.AllPies;

            piesListViewModel.CurrentCategory = "Cheese Cakes";
            return View(piesListViewModel);
        }

        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
            {
                return NotFound();
            }
            return View(pie);
        }
    }
}

X-sSweetShop/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<li class="dropdown nav-item">
    <a asp-controller="Pie" asp-action="Index" class="dropdown-toggle nav-link" data-toggle="dropdown">Pies</a>
    <ul class="dropdown-menu">
        @foreach (var category in Model)
        {
            <li>
                <a class="dropdown-item" asp-controller="Pie" asp-action="List" asp-route-category="@category.CategoryName">@category.CategoryName</a>
            </li>
        }
        <li class="dropdown-divider"></li>
        <li>
            <a class="dropdown-item" asp-controller="Pie" asp-action="List" asp-route-category="">View all pies</a>
        </li>
    </ul>
</li>